#!/usr/bin/env bash
# My Script here,does the following:
#   This creates a file /var/run/myscript.pid containing the script PID.
#   This display "To infinity and beyond" indefinitely
#   To display "I hate the kill command" upon receiving a SIGTERM
#   To displays"Y U no love me?!" upon receiving a SIGINT
#   This deletes the file /var/run/myscript.pid and terminates upon receiving SIGQUIT OR SIGTERM

terminator() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUITgit 
done
