#!/usr/bin/env bash
# This is to configure an Ubuntu Server to a localhost and facebook.

cp /etc/hosts ~/hosts.new
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
